### ISSUE TITLE
Some keys

### ISSUE THREAD

**Issue by caliburn420** [kingbased/keychecker#2]
Hi some quarantined AWS keys have either bedrock already available and already setup or keys that can be setupped on other regions which shows up as unusable here.

**Comment by kingbased** [comment]
Do you mean that quarantined keys are usable and the keychecker is reporting them as not due to quarantine? I can potentially see how AWS keys that are quarantined with claude already setup are usable, but I'm not sure how keys that require further setup would be usable since the quarantine should prevent any further actions on the key (like creating a user or activating bedrock etc). Then again I'm not versed on AWS so correct me if I'm wrong.

**Comment by caliburn420** [comment]
Hi there, yes some keys are quarantined with useable bedrock already, also some keys with quarantined status can still be used to set up on some other regions besides in the US (This is not universal though, but it happens)

**Comment by caliburn420** [comment]
Perhaps a separate category for quarantined keys at the minimum?

**Comment by kingbased** [comment]
> some keys are also not detected, those in the non US regions with an access already

i'm checking for valid keys across all bedrock enabled regions the same way, i'll need the key that's not working to try and fix this because it sounds like a weird aws thing.

> Also some keys with quarantined status can still be used to set up on some other regions besides in the US (This is not universal though, but it happens)

like above, probably going to need an example of a key that's like that because i have no idea how i would test for that without one.

for now i've ignored the quarantine flag on keys with bedrock enabled so they'll still be marked as valid, if you want to help me with those other issues and are willing to send over an example key you can find my email in a commits .patch and send me the key so i can run tests on it.

**Comment by caliburn420** [comment]
Sure please wait.
